// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opjofokaigbsuzepluln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wam9mb2thaWdic3V6ZXBsdWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjgxMzksImV4cCI6MjA2NjQ0NDEzOX0.48v65qVzxF1GfrYcwZ8owE8CRaearSoKmesxxOtYy1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);